targets:
  $default:
    sources:
      - lib/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          with_base_url: true
          with_converter: true
          use_required_attribute_for_headers: true
          ignore_headers: false
          use_default_null_for_lists: false
          build_only_models: false
          use_path_for_request_names: false
          include_if_null:
            enabled: true
            value: false
          input_folder: "lib/"
          output_folder: "lib/generated/"
          enums_case_sensitive: true
