name: ynab
description: A Dart client for working with the YNAB API
version: 0.0.2
repository: https://github.com/deriegle/ynab-dart

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  path: ^1.6.0
  json_annotation: ^3.0.1
  meta: ^1.2.4
  chopper: ^3.0.6
  http: ^0.12.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

  chopper_generator: ^4.0.0
  json_serializable: ^3.5.0
  build_runner: ^1.10.1